sudo: required
services:
  - docker

before_install:
  - docker build -t testimage -f ./client/Dockerfile.dev ./client

script: 
  - docker run -t testimage npm test -- --coverage

after_success:
  - docker build -t multi-client ./client
  - docker build -t multi-ngnix ./ngnix
  - docker build -t multi-server ./server
  - docker build -t multi-worker ./worker


  - echo "$DOCKER_PASSWORD" | docker login - u "$DOCKER_ID" --password-stdin
  - docker push multi-client
  - docker push multi-ngnix
  - docker push multi-server
  - docker push multi-worker