sudo: required
services:
  - docker

before_install:
  - docker build -t ahmaity/complex-client -f ./client/Dockerfile.dev ./client

script: 
  - docker run -t ahmaity/complex-client npm test -- --coverage

after_success:
  - docker build -t ahmaity/multi-client ./client
  - docker build -t ahmaity/multi-ngnix ./ngnix
  - docker build -t ahmaity/multi-server ./server
  - docker build -t ahmaity/multi-worker ./worker

#push images to docker hub
#login
- echo "$DOCKER_PASSWORD" | docker login - u "$DOCKER_ID" --password-stdin

#Take images and push them to docker hub
  - docker push ahmaity/multi-client
  - docker push ahmaity/multi-ngnix
  - docker push ahmaity/multi-server
  - docker push ahmaity/multi-worker

#